Sprint 2 : édition et affichage d'histoires
WildCodeSchool-2024-02/php-poec-paris-p2-herowebsite pull request #5
Opened 2024-06-06 15:57 UTC by AntoineSPR

Parties narration et création fonctionnelles mais sans style
Narration : les histoires s'affichent, les scènes sont chargées suivant les choix, les dialogues défilent.
Création : CRUD des histoires et des scènes, avec personnages, dialogues et choix

2024-06-06 21:10 UTC, mickaellambert requested changes
Ne vous faites pas avoir par le nombre de commentaires, c'est globalement du très bon travail, vous avez bien organisé votre code, tenter des choses et vous avez bien compris comment l'architecture MVC marche. 

Bravo pour tout ça !

2024-06-06 21:10 UTC, mickaellambert commented on .github/workflows/main.yml
Pas besoin de modifier ce fichier, c'est pour le déploiement du site

2024-06-06 21:10 UTC, mickaellambert commented on docker-compose.override.yml
Pas besoin de modifier ce fichier, c'est pour le déploiement du site

2024-06-06 21:10 UTC, mickaellambert commented on docker-compose.prod.yml
Pas besoin de modifier ce fichier, c'est pour le déploiement du site

2024-06-06 21:10 UTC, mickaellambert commented on docker-compose.yml
Pas besoin de modifier ce fichier, c'est pour le déploiement du site

2024-06-06 21:10 UTC, mickaellambert commented on public/assets/js/scene.js
Attention à ne pas polluer votre code de commentaires inutiles, il est censé être compréhensible sans

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/AbstractController.php
L'idée est bonne, mais malheureusement pas forcément la plus optimale. A chaque instanciation de controller, vous allez instancier plusieurs managers qui ne seront pas forcément utilisé dans les dits controller.

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/AbstractController.php
> +    public const EXTENSIONS_ALLOWED = ['jpg', 'jpeg', 'png', 'webp', 'svg'];
Ici, la constante n'est pas bien placé, est ce le type de fichier accepté pour le formulaire d'inscription et l'avatar, est ce le type de fichier accepté pour la création de dialogue, de sprite ? Je pourrai trouver d'autres idées mais globalement il vaut mieux placer cette constante dans le controlleur qu'elle concerne directement (et la nommer en conséquence)

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/CharacterController.php
> +                // Log des informations d'erreur
Commentaire inutile

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/CharacterController.php
> +                error_log('Erreurs lors de l\'ajout dtu sprite: ' . implode(', ', $errors));
Très bien de faire ça bravo

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/CharacterController.php
> +            if (!move_uploaded_file($_FILES['sprite']['tmp_name'], $targetFile)) {
Ne voulez vous pas réaliser l'upload du fichier que dans le cas ou il n'y a pas d'erreurs sur votre formulaire ?

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/CharacterController.php
> +            $character['name'] = $character['e_name'];
Pourquoi ne pas définir les attributs name de vos input directement à "name" et "sprite" ?

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/ChoiceController.php
> +            $choice['next_scene_id'] = $nextSceneId;
Pourquoi le next_scene_id est envoyé en GET et pas en POST ?

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/SceneController.php
> +            $targetDir = 'assets/images/backgrounds/';
Cette valeur pourrait être une constante dans votre controller

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/SceneController.php
> +                // Log des informations d'erreur
Même commentaire que précédemment, faites attentions aux commantaires de code inutile

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/SceneController.php
> +        $dialogues = $this->dialogueManager->getDialoguesBySceneId($sceneId);
Essayez de rester cohérents dans vos manager : les fonctions de selection de base commencent par le préfixe "select" et les votre par "get", ca peut rendre la chose plus confusante pour des développements futurs

Pas besoin de préciser la ressource concernée dans le nom, nous sommes déjà dans un dialogueManager.

Je verrai plus "selectAllByScene"

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/SceneController.php
> +        $choices = $this->choiceManager->getChoicesBySceneId($sceneId);
selectAllByScene

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/SceneController.php
> +    public function showFirstScene(int $storyId): string
Pourquoi existe-t-il une route qui permet d'afficher la première scène ? 
Il faudrait, lorsque vous cliquez sur le bouton "commencer une histoire" que vous fournissiez le lien vers la route show de base d'une scène avec l'id de la première scène. 
Ne pas ajouter un comportement différent dans un cas précis

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/SceneController.php
> +        $firstSceneId = $this->sceneManager->findFirstSceneIdOfStory($storyId);
La fonction devrait plutôt s'appeler "selectFirstByStory" et devrait retourner toutes les données d'une scène (sait on jamais, vous en aurez peut être besoin un jour)

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/SceneController.php
> +        return $this->show($storyId, $firstSceneId);
Du coup ici : 

`return $this->show($storyId, $firstScene['id']);`

2024-06-06 21:10 UTC, mickaellambert commented on src/Controller/StoryController.php
> +    public function indexCreation(): ?string
J'aurai mis les routes concernant les création d'histoires dans un autre controller "StoryCreation" ou même "Backoffice"

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/AbstractManager.php
Il ne faut pas toucher à ce fichier, le framework marche très bien comme il est

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/AbstractManager.php
> +    public function decodeHtmlEntitiesInArray(array|null $array): ?array
Je comprends pas trop le probleme que vous essayez de résoudre ici

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/DialogueManager.php
> +    public function getDialogues(string $id): ?array
Vous pouvez surcharger la fonction selectAll() présente dans l'Abstract

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/DialogueManager.php
> +    public function getDialoguesBySceneId(int $sceneId): ?array
Voir commentaire plus haut

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/SceneManager.php
> +    public function getStory(string $id): ?array
Pourquoi rajouter une fonction qui récupère une histoire dans un SceneManager ? 
De plus, il existe déjà la fonction selectOneById sur tout vos managers

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/SceneManager.php
> +    public function findScene(int $storyId, int $sceneId): array|false
Pourquoi ajouter le storyId dans vos critères de recherches ? Cela marcherait très bien avec juste l'ID de la scene et donc pas besoin de créer une nouvelle fonction

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/SceneManager.php
> +    public function findFirstSceneIdOfStory(int $storyId): int|false
Voir commentaire plus haut

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/SceneManager.php
> +    public function selectAllByStoryId(string $storyId): array
selectAllByStory()

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/StoryManager.php
> +    public const TABLE = "`story`";
Ca ne marche pas comme ça ? `public const TABLE = "story";`

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/StoryManager.php
> +    public function getScenes(string $storyId): ?array
selectScenes

2024-06-06 21:10 UTC, mickaellambert commented on src/Model/StoryManager.php
> +    // Hérite de la méthode SelectAll pour récupérer toutes les histoires après défintion de la table
commentaire inutile

2024-06-06 21:10 UTC, mickaellambert commented on src/routes.php
> +    'storycreation' => ['StoryController', 'indexCreation'],
Ca me parait plus cohérent de faire des routes ressemblant à ça : /story/admin/

Pas obligé, qu'en pensez vous ?

2024-06-06 21:10 UTC, mickaellambert commented on src/routes.php
> +    'storycreation/addchar' => ['CharacterController', 'add', ['story_id', 'scene_id']],
Si vous faites des routes en séparant les mots par des "_" au dessus, pensez bien à le faire partout.

2024-06-06 21:10 UTC, mickaellambert commented on src/routes.php
> +    'storycreation/scene/add_dial' => ['DialogueController', 'add', ['story_id', 'scene_id']],
Que pensez vous de `story/admin/scene/dialogue/add` comme format global de routes ?

2024-06-06 21:10 UTC, mickaellambert commented on src/routing.php
Attention aux fichiers que vous envoyez avec des modifs toute simple comme celle ci

2024-06-07 08:13 UTC, Amine03824 commented on .github/workflows/main.yml
C'était obligatoire de mettre la nouvelle version de php sinon depuis hier soir plus rien ne passait les checks
![image](https://github.com/WildCodeSchool-2024-02/php-poec-paris-p2-herowebsite/assets/137644798/09f49ac7-2363-43b7-9f3c-878d2dd88605)
![image](https://github.com/WildCodeSchool-2024-02/php-poec-paris-p2-herowebsite/assets/137644798/9a64f2cd-1b09-4fe0-a7a9-c6e1e5b19d41)

le principal changement est au niveau de la version php pour github actions 
![image](https://github.com/WildCodeSchool-2024-02/php-poec-paris-p2-herowebsite/assets/137644798/43b05ac2-b226-4969-93ba-098b11561291)

2024-06-11 14:15 UTC, merged